const datosLecciones = {
  lecciones: [
    {
      id: 1,
      nombre: "leccion 1",
      palabras: [
        { aleman: "der Onkel", espanol: "el tío" },
        { aleman: "die Tante", espanol: "la tía" },
        { aleman: "die Großeltern", espanol: "los abuelos" },
        { aleman: "der Opa", espanol: "el abuelo" },
        { aleman: "die Kinder", espanol: "lols hijos" },
        { aleman: "der Bruder", espanol: "el hermano" },
        { aleman: "die Schwester", espanol: "la hermana" },
        { aleman: "die Geschwister", espanol: "los hermanos" },
        { aleman: "die Oma", espanol: "la abuela" },
        { aleman: "die Familie", espanol: "la familia" },
        { aleman: "die Mutter", espanol: "la madre" },
        { aleman: "die Eltern", espanol: "los padres" },
        { aleman: "der Vater", espanol: "el padre" },
        { aleman: "arbeitslos", espanol: "desempleado" },
        { aleman: "arbeiten", espanol: "trabajar" },
        { aleman: "der Beruf", espanol: "la profesión" },
        { aleman: "die Lehrerin", espanol: "la maestra" },
        { aleman: "der Lehrer", espanol: "el maestro" },
        { aleman: "die Hausfrau", espanol: "la ama de casa" },
        { aleman: "der Hasusmann", espanol: "el amo de casa" },
        { aleman: "der Cousin", espanol: "el primo" },
        { aleman: "die Cousine", espanol: "la prima" },
        { aleman: "der Arzt", espanol: "el médico" },
        { aleman: "die Ärztin", espanol: "la médica" },
        { aleman: "die Wohnung", espanol: "el piso" },
        { aleman: "helfen", espanol: "azudar" },
        { aleman: "im Garten", espanol: "en el jardäin" },
        { aleman: "aufräumen", espanol: "ordenar" },
        { aleman: "zu Hause bleiben", espanol: "quedarse en casa" },
        { aleman: "das Zimmer", espanol: "la habitaciäon" },
        { aleman: "die Küche", espanol: "la cocina" },
        { aleman: "das Schlafzimmer", espanol: "el dormitorio" },
        { aleman: "das Bad", espanol: "el baño" },
        { aleman: "Was machen sie?", espanol: "¿Qué hacen ellas?" },
        { aleman: "kochen", espanol: "cocinar" },
        { aleman: "trinken", espanol: "beber" },
        { aleman: "essen", espanol: "comer" },
        { aleman: "meine Haustiere", espanol: "mis mascotas" },
        { aleman: "das Haustier", espanol: "la mascota" },
        { aleman: "der Fisch", espanol: "el pez" },
        { aleman: "der Hund", espanol: "el perro" },
        { aleman: "das Pferd", espanol: "el caballo" },
        { aleman: "reiten", espanol: "montar a caballo" },
        { aleman: "die Katze", espanol: "el gato" },
        { aleman: "aussehen", espanol: "verse" },
        { aleman: "nett,", espanol: "amable" }, 
        { aleman: "sympathisch", espanol: "simpático" },
        { aleman: "alt", espanol: "viejo" },
        { aleman: "jung", espanol: "joven" },
        { aleman: "groß", espanol: "grande" },
        { aleman: "klein", espanol: "pequeño" },
        { aleman: "lieb", espanol: "agradable" },
        { aleman: "intelligent", espanol: "inteligente" },
        { aleman: "sportlich", espanol: "deportista" },
        { aleman: "faul", espanol: "perezoso" },
        { aleman: "streng", espanol: "estricto" },
        { aleman: "süß", espanol: "dulce" },
        { aleman: "wohnen", espanol: "vivir" },
        { aleman: "leben", espanol: "vivir" },
        { aleman: "im See", espanol: "en el lago" },
        { aleman: "im Haus", espanol: "en la casa" },
        { aleman: "in meinem Zimmer", espanol: "en mi habitación" },
        { aleman: "krank", espanol: "enfermo" },
        { aleman: "Schmerzen haben", espanol: "tener dolores" },
        { aleman: "zum Tierarzt bringen", espanol: "llevar al veterinario" },
        { aleman: "glücklich", espanol: "feliz" },
        { aleman: "traurig", espanol: "triste" },
        { aleman: "mögen", espanol: "gustar" },
        { aleman: "heiraten", espanol: "casarse" },
        { aleman: "die Hochzeit", espanol: "la boda" },
        { aleman: "der Glückwunsch", espanol: "la felicitación" },
        { aleman: "lieben", espanol: "amar" },
        { aleman: "heißen", espanol: "llamarse" },
        { aleman: "der Vorname", espanol: "el nombre" },
        { aleman: "der Familienname", espanol: "el apellido" },
        { aleman: "der Geburtstag", espanol: "el cumpleaños" },
        { aleman: "das Alter", espanol: "la edad" },
        { aleman: "geboren sein", espanol: "nacer" },
        { aleman: "die Party", espanol: "la fiesta" },
        { aleman: "das Brot", espanol: "el pan" },
        { aleman: "spielen", espanol: "jugar" },
        { aleman: "das Wasser", espanol: "el agua" },
        { aleman: "das Fleisch", espanol: "la carne" },
        { aleman: "die Telefonnummer", espanol: "el número de teléfono" },
        { aleman: "die E-Mail-Adresse", espanol: "la dirección de correo electrónico" }
      ]
    },
    {
      id: 2,
      nombre: "leccion 2",
      palabras: [
          
  {aleman: "ausgehen, geht aus", espanol: "salir"},
  {aleman: "in die Disko", espanol: "a la discoteca"},
  {aleman: "tanzen", espanol: "bailar"},
  {aleman: "ins Kino", espanol: "al cine"},
  {aleman: "einen Film sehen", espanol: "ver una película"},
  {aleman: "der Ausflug, die Ausflüge (pl)", espanol: "la excursión"},
  {aleman: "fahren, fährt", espanol: "conducir, ir en un vehículo"},
  {aleman: "mit dem Auto", espanol: "en coche"},
  {aleman: "mit dem Rad", espanol: "en bici"},
  {aleman: "einsteigen, steigt ein", espanol: "subirse en un vehículo"},
  {aleman: "mit dem Schiff", espanol: "en barco"},
  {aleman: "mit dem Zug", espanol: "en tren"},
  {aleman: "mitnehmen, nimmt mit", espanol: "llevar"},
  {aleman: "der Fotoapparat", espanol: "la cámara"},
  {aleman: "die Fahrtkarte", espanol: "el billete (de viaje)"},
  {aleman: "der Rucksack", espanol: "la mochila"},
  {aleman: "Wann?", espanol: "¿Cuándo?"},
  {aleman: "am Wochenende", espanol: "el fin de semana"},
  {aleman: "am Montag", espanol: "el lunes"},
  {aleman: "dreimal in der Woche", espanol: "tres veces a la semana"},
  {aleman: "jeden Tag", espanol: "todos los días"},
  {aleman: "jede Woche", espanol: "todas las semanas"},
  {aleman: "die Musik", espanol: "la música"},
  {aleman: "Musik hören", espanol: "escuchar música"},
  {aleman: "Musik machen", espanol: "hacer música"},
  {aleman: "in einer Band spielen", espanol: "tocar en una banda"},
  {aleman: "Klavier spielen", espanol: "tocar el piano"},
  {aleman: "die Popmusik", espanol: "la música pop"},
  {aleman: "Hobbys zu Hause", espanol: "Hobbis en casa"},
  {aleman: "Computer spielen", espanol: "jugar al ordenador"},
  {aleman: "fernsehen", espanol: "ver la tele"},
  {aleman: "im Internet surfen", espanol: "navegar en internet"},
  {aleman: "basteln", espanol: "hacer manualidades"},
  {aleman: "etwas sammeln", espanol: "coleccionar algo"},
  {aleman: "lesen, liest", espanol: "leer"},
  {aleman: "die Krimis", espanol: "las novelas policiacas"},
  {aleman: "der Comic", espanol: "el cómic"},
  {aleman: "das Rätsel", espanol: "la adivinanza"},
  {aleman: "die Zeitung", espanol: "el periódico"},
  {aleman: "das Buch", espanol: "el libro"},
  {aleman: "Wie ist das?", espanol: "¿Cómo es esto?"},
  {aleman: "einfach", espanol: "fácil"},
  {aleman: "interessant", espanol: "interesante"},
  {aleman: "gefallen", espanol: "gustar"},
  {aleman: "schwer", espanol: "difícil"},
  {aleman: "mögen", espanol: "gustar"},
  {aleman: "Wo?", espanol: "¿Dónde?"},
  {aleman: "am Strand", espanol: "en la playa"},
  {aleman: "im Wald", espanol: "en el bosque"},
  {aleman: "im Schwimmbad", espanol: "en la piscina"},
  {aleman: "im Garten", espanol: "en el jardin"},
  {aleman: "am See", espanol: "en el lago"},
  {aleman: "im Park", espanol: "en el parque"},
  {aleman: "der Sport", espanol: "el deporte"},
  {aleman: "spazieren gehen", espanol: "pasear"},
  {aleman: "Tennis spielen", espanol: "jugar al tenis"},
  {aleman: "Basketball spielen", espanol: "jugar al baloncesto"},
  {aleman: "schwimmen", espanol: "nadar"},
  {aleman: "das Bikini", espanol: "el biquini"},
  {aleman: "reiten, reitet", espanol: "montar a caballo"},
  {aleman: "wandern", espanol: "hacer senderismo"}
]
    },
   {
      id: 3,
      nombre: "leccion 3",
      palabras: [
        { aleman: "der Unterricht", espanol: "la clase" },
{ aleman: "die Hausaufgabe, die Hausaufgaben (pl)", espanol: "la tarea" },
{ aleman: "die Stunde, die Stunden (pl)", espanol: "la hora" },
{ aleman: "die Note, die Noten (pl)", espanol: "la nota" },
{ aleman: "das Zeugnis, die Zeugnisse (pl)", espanol: "notas, certificado," },
{ aleman: "die Übung, die Übungen (pl)", espanol: "el ejercicio" },
{ aleman: "die Aufgabe, die Aufgaben (pl)", espanol: "la tarea" },
{ aleman: "das Beispiel, die Beispiele (pl)", espanol: "el ejemplo" },
{ aleman: "der Fehler, die Fehler (pl)", espanol: "el error" },
{ aleman: "nicht richtig", espanol: "incorrecto" },
{ aleman: "falsch", espanol: "incorrecto" },
{ aleman: "Wie ist das?", espanol: "¿Cómo es esto?" },
{ aleman: "langweilig/interessant", espanol: "aburrido/interesante" },
{ aleman: "einfach/schwer", espanol: "fácil/difícil" },
{ aleman: "wie oft?", espanol: "¿Con qué frecuencia?" },
{ aleman: "immer", espanol: "siempre" },
{ aleman: "oft", espanol: "a menudo" },
{ aleman: "nie", espanol: "nunca" },
{ aleman: "manchmal", espanol: "algunas veces" },
{ aleman: "Das machen wir.", espanol: "Nosotros hacemos esto" },
{ aleman: "fragen", espanol: "preguntar" },
{ aleman: "antworten", espanol: "responder" },
{ aleman: "sprechen", espanol: "hablar" },
{ aleman: "wiederholen", espanol: "repetir" },
{ aleman: "arbeiten", espanol: "trabajar" },
{ aleman: "helfen, hilft,", espanol: "ayudar" },
{ aleman: "hören", espanol: "oir, escuchar" },
{ aleman: "verstehen, versteht", espanol: "entender" },
{ aleman: "schreiben, schreibt", espanol: "escribir" },
{ aleman: "lesen, liest", espanol: "leer" },
{ aleman: "lernen, lernt", espanol: "aprender" },
{ aleman: "die Pause", espanol: "el recreo" },
{ aleman: "frei haben", espanol: "tener tiempo libre" },
{ aleman: "die Zeit", espanol: "el tiempo" },
{ aleman: "morgen", espanol: "mañana" },
{ aleman: "heute", espanol: "hoy" },
{ aleman: "pünktlich", espanol: "puntual" },
{ aleman: "gestern", espanol: "ayer" },
{ aleman: "aus sein: Die Schule ist aus", espanol: "terminar" },
{ aleman: "anfangen, fängt an", espanol: "empezar" },
{ aleman: "die Personen", espanol: "las personas" },
{ aleman: "der Lehrer, die Lehrer (pl)", espanol: "el profesor, el maestro" },
{ aleman: "erklären", espanol: "explicar" },
{ aleman: "zeigen", espanol: "enseñar, mostrar" },
{ aleman: "Ruhe bitte!", espanol: "Silencio, por favor" },
{ aleman: "Wie sind die Personen?", espanol: "¿Cómo son las personas?" },
{ aleman: "freundlich", espanol: "amable" },
{ aleman: "nett", espanol: "agradable" },
{ aleman: "blöd", espanol: "tonto, aburrido" },
{ aleman: "lustig", espanol: "divertido" },
{ aleman: "dumm", espanol: "tonto" },
{ aleman: "neu", espanol: "nuevo" },
{ aleman: "sympathisch", espanol: "simpático" },
{ aleman: "der/die Beste", espanol: "el/la mejor" },
{ aleman: "der Schüler, die Schüler (pl)", espanol: "el alumno" },
{ aleman: "die Schülerin, die Schülerinnen (pl)", espanol: "la alumna" },
{ aleman: "Quatsch machen", espanol: "hacer tonterías" },
{ aleman: "schlafen, schläft", espanol: "dormir" },
{ aleman: "aufpassen", espanol: "prestar atención" },
{ aleman: "die Schulart", espanol: "el tipo de colegio" },
{ aleman: "die Sprachenschule", espanol: "escuela de idiomas" },
{ aleman: "die Grundschule", espanol: "escuela primaria" },
{ aleman: "die Hauptschule", espanol: "secundaria básica" },
{ aleman: "das Gymnasium", espanol: "el instituto" },
{ aleman: "die Schulsachen", espanol: "el material escolar" },
{ aleman: "der Bleistift, die Bleistifte (pl)", espanol: "lápiz" },
{ aleman: "der Kugelschreiber", espanol: "el bolígrafo" },
{ aleman: "der Radiergummi, die Radiergummis (pl)", espanol: "la goma de borrar" },
{ aleman: "das Buch, die Bücher (pl)", espanol: "el libro" },
{ aleman: "das Heft, die Hefte", espanol: "cuaderno" },
{ aleman: "der Schulranzen", espanol: "la mochila" },
{ aleman: "das Fach, die Fächer (pl)", espanol: "la asignatura" },
{ aleman: "Deutsch", espanol: "alemán" },
{ aleman: "das Lieblingsfach", espanol: "la asignatura favorita" },
{ aleman: "Sport", espanol: "educación física" },
{ aleman: "Geschichte", espanol: "historia" },
{ aleman: "Chemie", espanol: "química" },
{ aleman: "Physik", espanol: "física" },
{ aleman: "Sozialkunde", espanol: "sociales" },
{ aleman: "Geografie", espanol: "geografía" },
{ aleman: "Englisch", espanol: "inglés" },
{ aleman: "Mathe", espanol: "matemáticas" }
      ]
    },
   {
      id: 4,
      nombre: "leccion 4",
      palabras: [
        { aleman: "Wo?", espanol: "¿Dónde?" },
{ aleman: "im Konzert", espanol: "en el concierto" },
{ aleman: "im Theater", espanol: "en el teatro" },
{ aleman: "im Kino", espanol: "en el cine" },
{ aleman: "fernsehen, sieht fern", espanol: "ver la tele" },
{ aleman: "im Fernsehen", espanol: "en la tele" },
{ aleman: "das Video", espanol: "el vídeo" },
{ aleman: "das DVD, die DVDs", espanol: "el DVD" },
{ aleman: "Musik hören", espanol: "escuchar música" },
{ aleman: "das CD, die CDs", espanol: "el CD" },
{ aleman: "im Radio", espanol: "en el radio" },
{ aleman: "die Kassette, die Kassetten", espanol: "la cinta de casette" },
{ aleman: "der Walkman", espanol: "el walkman" },
{ aleman: "die Post", espanol: "oficina de correos" },
{ aleman: "die Postkarte, die Postkarten", espanol: "tarjeta postal" },
{ aleman: "der Brief, die Briefe", espanol: "la carta" },
{ aleman: "eine Postkarte schicken", espanol: "enviar una postal" },
{ aleman: "einen Brief schreiben", espanol: "escribir una carta" },
{ aleman: "einen Brief lesen", espanol: "leer una carta" },
{ aleman: "eine Postkarte bekommen", espanol: "recibir una postal" },
{ aleman: "der Computer", espanol: "el ordenador" },
{ aleman: "Computerspiele spielen", espanol: "jugar en el ordenador" },
{ aleman: "das Internet", espanol: "el internet" },
{ aleman: "Informationen bekommen", espanol: "conseguir informaciones" },
{ aleman: "Informationen suchen", espanol: "buscar informaciones" },
{ aleman: "die E-Mail", espanol: "el correo electrónico" },
{ aleman: "eine E-Mail lesen", espanol: "leer un e-mail" },
{ aleman: "eine E-Mail schreiben", espanol: "escribir un e-mail" },
{ aleman: "eine E-Mail schicken", espanol: "enviar un e-mail" },
{ aleman: "eine E-Mail bekommen", espanol: "recibir un e.mail" },
{ aleman: "Wie ist...?", espanol: "¿Cómo es...?" },
{ aleman: "toll", espanol: "genial" },
{ aleman: "traurig", espanol: "triste" },
{ aleman: "lustig", espanol: "divertido" },
{ aleman: "interessant/langweilig", espanol: "interesante/aburrido" },
{ aleman: "kurz/lang", espanol: "corto/largo" },
{ aleman: "schön", espanol: "bonito" },
{ aleman: "das Handy", espanol: "el móvil" },
{ aleman: "das SMS", espanol: "el SMS" },
{ aleman: "ein SMS schreiben", espanol: "escribir un SMS" },
{ aleman: "ein SMS lesen", espanol: "leer un SMS" },
{ aleman: "ein SMS schicken", espanol: "enviar un SMS" },
{ aleman: "ein SMS bekommen", espanol: "recibir un SMS" },
{ aleman: "das Telefon", espanol: "el teléfono" },
{ aleman: "am Telefon sprechen", espanol: "hablar por teléfono" },
{ aleman: "telefonieren", espanol: "hablar por teléfono" },
{ aleman: "anrufen, ruft an", espanol: "Ilamar por teléfono" },
{ aleman: "das Comic", espanol: "el cómic" },
{ aleman: "das Buch, die Bücher", espanol: "el libro" },
{ aleman: "die Zeitung, die Zeitungen", espanol: "el periódico" }
        
      ]
    },
    {
      id: 5,
      nombre: "leccion 5",
      palabras: [
        { aleman: "kochen, kocht", espanol: "cocinar, hervir" },
{ aleman: "die Suppe", espanol: "la sopa" },
{ aleman: "das Ei, die Eier", espanol: "el huevo" },
{ aleman: "der Tee", espanol: "el té" },
{ aleman: "das Wasser", espanol: "el agua" },
{ aleman: "Wo kann man etwas essen und trinken?", espanol: "¿Dónde se puede comer o beber algo?" },
{ aleman: "zu Hause", espanol: "en casa" },
{ aleman: "in der Schule", espanol: "en el colegio" },
{ aleman: "im Garten", espanol: "en el jardin" },
{ aleman: "in der Küche", espanol: "en la cocina" },
{ aleman: "im Lokal", espanol: "en el restaurante" },
{ aleman: "der Hunger", espanol: "el hambre" },
{ aleman: "das Brot", espanol: "el pan" },
{ aleman: "der Käse", espanol: "el queso" },
{ aleman: "die Pizza", espanol: "la pizza" },
{ aleman: "es schmeckt", espanol: "sabe (gusto)" },
{ aleman: "nicht gut", espanol: "mal" },
{ aleman: "wunderbar", espanol: "estupendo" },
{ aleman: "toll", espanol: "genial" },
{ aleman: "gut", espanol: "bueno" },
{ aleman: "zum Frühstück", espanol: "para desayunar" },
{ aleman: "das Brötchen, die Brötchen", espanol: "el panecillo" },
{ aleman: "frühstücken, frühstückt", espanol: "desayunar" },
{ aleman: "die Milch", espanol: "la leche" },
{ aleman: "der Kakao", espanol: "la leche con cacao" },
{ aleman: "die Marmelade", espanol: "la mermelada" },
{ aleman: "der Saft", espanol: "el zumo" },
{ aleman: "zu Mittag", espanol: "al mediodía" },
{ aleman: "das Gemüse", espanol: "la verdura" },
{ aleman: "das Fleisch", espanol: "la carne" },
{ aleman: "der Fisch", espanol: "el pescado" },
{ aleman: "die Kartoffeln", espanol: "las patatas" },
{ aleman: "am Abend", espanol: "por la noche" },
{ aleman: "der Salat", espanol: "la ensalada" },
{ aleman: "Wie ist...?", espanol: "¿Cómo está...?" },
{ aleman: "süß", espanol: "dulce" },
{ aleman: "warm", espanol: "caliente" },
{ aleman: "kalt", espanol: "frío" },
{ aleman: "der Durst", espanol: "la sed" },
{ aleman: "das Glas", espanol: "el vaso" },
{ aleman: "der Kaffee", espanol: "el café" },
{ aleman: "das Mineralwasser", espanol: "el agua mineral" },
{ aleman: "der Saft, die Säfte", espanol: "zumo" },
{ aleman: "die Tasse, die Tassen", espanol: "la taza" },
{ aleman: "die Milch", espanol: "la leche" },
{ aleman: "die Flasche", espanol: "la botella" },
{ aleman: "das Geld", espanol: "el dinero" },
{ aleman: "kosten, kostet", espanol: "costar" },
{ aleman: "teuer/billig", espanol: "caro/barato" },
{ aleman: "bezahlen, bezahlt", espanol: "pagar" },
{ aleman: "am Kiosk", espanol: "en el quiosco" },
{ aleman: "die Zeitung, die Zeitungen", espanol: "el periódico" },
{ aleman: "Wer kann einkaufen?", espanol: "¿Quién puede comprar?" },
{ aleman: "meine Eltern", espanol: "mis padres" },
{ aleman: "meine Mutter", espanol: "mi madre" },
{ aleman: "mein Vater", espanol: "mi padre" },
{ aleman: "Wann kann man einkaufen?", espanol: "¿Cuándo se puede comprar?" },
{ aleman: "geschlossen, offen", espanol: "cerrado/abierto" },
{ aleman: "machmal", espanol: "a veces" },
{ aleman: "einmal,zweimal in der Woche", espanol: "una o dos veces a la semana" },
{ aleman: "am Samstag", espanol: "el sábado" },
{ aleman: "am Vormittag", espanol: "a media mañana" },
{ aleman: "jeden Freitag", espanol: "cada viernes" },
{ aleman: "Was kann man im Geschäft kaufen?", espanol: "¿Qué se puede comprar en la tienda?" },
{ aleman: "die Jacke, die Jacken", espanol: "la chaqueta" },
{ aleman: "das Geschenk, die Geschenke", espanol: "el regalo" },
{ aleman: "der Ring, die Ringe", espanol: "el anillo" },
{ aleman: "die Jeans, die Jeans", espanol: "el pantalón vaquero" },
{ aleman: "das Kleid, die Kleider", espanol: "el vestido" },
{ aleman: "der Mantel, die Mäntel", espanol: "el abrigo" },
{ aleman: "das Bikini, die Bikinis", espanol: "el bikini" },
{ aleman: "Was kann man im Supermarkt einkaufen?", espanol: "¿Qué se puede comprar en el supermer-cado?" },
{ aleman: "das Fleisch", espanol: "carne" },
{ aleman: "die Wurst", espanol: "salchicha, embutido" },
{ aleman: "der Kuchen, die Kuchen", espanol: "el pastel" },
{ aleman: "der Quark", espanol: "requesón" },
{ aleman: "die Schokolade", espanol: "el chocolate" },
{ aleman: "der Salat", espanol: "la ensalada" },
{ aleman: "die Marmelade", espanol: "la mermelada" },
{ aleman: "der Saft, die Säfte", espanol: "el zumo" },
{ aleman: "das Brot", espanol: "el pan" },
{ aleman: "die Eier", espanol: "los huevos" },
{ aleman: "das Eis", espanol: "el helado" },
{ aleman: "Was kann man auf dem Markt einkaufen?", espanol: "¿Qué se puede comprar en el mercado?" },
{ aleman: "die Blume, die Blumen", espanol: "flor" },
{ aleman: "das Gemüse", espanol: "verdura" },
{ aleman: "die Kartoffel, die Kartoffeln", espanol: "patata" },
{ aleman: "die Tomate, die Tomaten", espanol: "tomate" },
{ aleman: "das Obst", espanol: "fruta" },
{ aleman: "der Apfel, die Äpfel", espanol: "la manzana" },
{ aleman: "die Banane, die Bananen", espanol: "el plátano" }
        
      ]
    },
{
      id: 6,
      nombre: "leccion 6 ",
      palabras: [
        { aleman: "die Stadt", espanol: "la ciudad" },
{ aleman: "der Spielplatz, die Spielplätze", espanol: "el parque infantil" },
{ aleman: "laufen, läuft", espanol: "correr" },
{ aleman: "spielen, spielt", espanol: "jugar" },
{ aleman: "die Straße, die Straßen", espanol: "la calle" },
{ aleman: "der Bus, die Busse", espanol: "el autobús" },
{ aleman: "das Auto, die Autos", espanol: "el coche" },
{ aleman: "das Fahrrad, die Fahrräder", espanol: "la bicicleta" },
{ aleman: "das Geschäft, die Geschäfte", espanol: "tienda" },
{ aleman: "die Post", espanol: "oficina de correos" },
{ aleman: "der Supermarkt, die Supermärkte", espanol: "el supermercado" },
{ aleman: "der Platz, die Plätze", espanol: "la plaza" },
{ aleman: "der Baum, die Bäume", espanol: "el árbol" },
{ aleman: "der Garten", espanol: "el jardín" },
{ aleman: "die Blumen gießen", espanol: "regar las flores" },
{ aleman: "die Adresse", espanol: "la dirección" },
{ aleman: "wohnen", espanol: "vivir" },
{ aleman: "am Park", espanol: "junto al parque" },
{ aleman: "in der Kafkastraße", espanol: "en la calle Kafka" },
{ aleman: "die Wohnung", espanol: "la vivienda, el piso" },
{ aleman: "das Schlafzimmer", espanol: "el dormitorio" },
{ aleman: "das Bad", espanol: "el baño" },
{ aleman: "das Wohnzimmer", espanol: "el salón" },
{ aleman: "die Küche", espanol: "la cocina" },
{ aleman: "mein Zimmer", espanol: "mi habitación" },
{ aleman: "das Bett, die Betten", espanol: "la cama" },
{ aleman: "schlafen, schläft", espanol: "dormir" },
{ aleman: "aufstehen, steht auf", espanol: "levantarse" },
{ aleman: "lesen, liest", espanol: "leer" },
{ aleman: "der Computer", espanol: "el ordenador" },
{ aleman: "im Internet surfen", espanol: "navegar en internet" },
{ aleman: "Hausaufgaben machen", espanol: "hacer los deberes" },
{ aleman: "das Radio", espanol: "la radio" },
{ aleman: "Musik hören", espanol: "escuchar música" },
{ aleman: "der Tisch", espanol: "la mesa" },
{ aleman: "lernenm lernt", espanol: "estudiar" },
{ aleman: "die Haltestelle", espanol: "la parada" },
{ aleman: "die Bahn, der Zug", espanol: "el tren" },
{ aleman: "der Bus", espanol: "el autobús" },
{ aleman: "die U-Bahn", espanol: "el metro" },
{ aleman: "halten, hält", espanol: "parar" },
{ aleman: "abfahren", espanol: "salir" },
{ aleman: "spazieren gehen, geht spazieren", espanol: "pasear" },
{ aleman: "in der Stadt", espanol: "en la ciudad" },
{ aleman: "im Wald", espanol: "en el bosque" },
{ aleman: "im Park", espanol: "en el parque" }
        
        
      ]
    },
    {
      id: 7,
      nombre: "leccion 7 ",
      palabras: [
        { aleman: "Was machen wir?", espanol: "¿Qué hacemos?" },
{ aleman: "kennenlernen, lernt kennen", espanol: "conocer por primera vez" },
{ aleman: "schwimmen, schwimmt", espanol: "nadar" },
{ aleman: "schreiben, schreibt", espanol: "escribir" },
{ aleman: "die Postkarte", espanol: "la postal" },
{ aleman: "wandern, wandert", espanol: "hacer senderismo" },
{ aleman: "lachen, lacht", espanol: "reir" },
{ aleman: "mitnehmen, nimmt mit", espanol: "llevar" },
{ aleman: "der Fotoapparat, die Fotoapparate", espanol: "la cámara de fotos" },
{ aleman: "der Rucksack, die Rucksäcke", espanol: "la mochila" },
{ aleman: "das Geld", espanol: "el dinero" },
{ aleman: "suchen und finden", espanol: "buscar y encontrar" },
{ aleman: "rechts", espanol: "a la derecha" },
{ aleman: "links", espanol: "a la izquierda" },
{ aleman: "geradeaus", espanol: "todo recto" },
{ aleman: "Wohin?", espanol: "¿A dónde?" },
{ aleman: "nach Europa", espanol: "a Europa" },
{ aleman: "nach England, Italien, Griechen-land", espanol: "a Inglaterra, Italia, Grecia" },
{ aleman: "in den Wald gehen", espanol: "ir al bosque" },
{ aleman: "an einen See fahren", espanol: "ir a un lago" },
{ aleman: "an den Strand fahren", espanol: "ir a la playa" },
{ aleman: "auf eine Insel fliegen", espanol: "volar a una isla" },
{ aleman: "Wann?", espanol: "¿Cuándo?" },
{ aleman: "im Juli", espanol: "en julio" },
{ aleman: "im Frühling, Sommer, Herbst, Winter", espanol: "en primavera, verano, otoño, invierno" },
{ aleman: "am Wochenende", espanol: "el fin de semana" },
{ aleman: "Wie?", espanol: "¿Cómo?" },
{ aleman: "mit dem Zug", espanol: "en tren" },
{ aleman: "der Fahrplan, die Fahrpläne", espanol: "el horario" },
{ aleman: "der Gleis, die Gleise", espanol: "la vía" },
{ aleman: "abfahren, fährt ab", espanol: "salir, partir" },
{ aleman: "die Fahrkarte, die Fahrkarten", espanol: "el billete (de viaje)" }
      ]
    }
  ]
};